window.WELL_PRODUCTS = [
  { brand:'Nike', name:'Nike ZoomX preto', sizes:[36,37], cardNote:'4 pares disponíveis', note:'2 pares no tam. 36 · 2 pares no tam. 37', price:170, image:'img/ready-nike-zoomx-preto.jpg' },
  { brand:'Nike', name:'Nike ZoomX bege/prata', sizes:[40], note:'', price:150, image:'img/ready-nike-zoomx-bege-prata.jpg' },
  { brand:'Nike', name:'Nike ZoomX Invincible Run 3 azul', sizes:[40,41], cardNote:'3 pares disponíveis', note:'1 par no tam. 40 · 2 pares no tam. 41', price:150, image:'img/ready-nike-zoomx-invincible-azul.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 preto', sizes:[39,41], note:'', price:250, image:'img/ready-af1-preto.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 branco', sizes:[37,41], cardNote:'cadarços extras', note:'Tam. 37: opções com cadarços branco trançado/normal ou cetim creme/branco · tam. 41: 2 cadarços brancos', price:250, image:'img/ready-af1-branco-37-trancado.jpg', images:['img/ready-af1-branco-37-trancado.jpg','img/ready-af1-branco-37.jpg','img/ready-af1-branco-41.jpg'] },
  { brand:'Nike', name:'Nike Air Force 1 cinza', sizes:[41,43], note:'', price:250, image:'img/produto-af1-cinza.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 bege/rosa', sizes:[36], note:'2 tipos de cadarço', price:250, image:'img/ready-af1-bege-rosa.jpg' },
  { brand:'Nike', name:'Nike AF1 Shadow azul/rosa', sizes:[37], note:'cadarços de cetim e branco', price:250, image:'img/ready-af1-shadow-azul-rosa.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 preto/branco', sizes:[38], note:'2 cadarços: preto e creme', price:250, image:'img/ready-af1-panda.jpg' },
  { brand:'Nike', name:'Nike AF1 plataforma azul', sizes:[36,37], note:'2 cadarços: azul e branco', price:250, image:'img/ready-af1-plataforma-azul.jpg' },
  { brand:'Nike', name:'Nike Court branco/azul', sizes:[37,39], note:'2 cadarços: azul e branco', price:250, image:'img/ready-nike-court-branco-azul.jpg' },
  { brand:'Adidas', name:'Adidas Samba', sizes:[37], note:'2 cadarços: branco e preto', price:170, image:'img/ready-adidas-samba.jpg' },
  { brand:'Adidas', name:'Adidas SL72 areia', sizes:[37], note:'2 cadarços: branco e preto', price:250, image:'img/ready-adidas-sl72-areia.jpg' },
  { brand:'Adidas', name:'Adidas SL72 bordô', sizes:[38], note:'feminino', price:250, image:'img/ready-adidas-sl72-bordo.jpg' },
  { brand:'Adidas', name:'Adidas feminino branco', sizes:[36,37,39], cardNote:'4 pares disponíveis', note:'1 par no tam. 36 · 2 pares no tam. 37 · 1 par no tam. 39', price:170, image:'img/ready-adidas-feminino-branco.jpg' },
  { brand:'On Cloud', name:'On Cloud preto', sizes:[36,37], note:'', price:null, image:'img/produto-on-cloud-preto.jpg' },
  { brand:'Nike', name:'Nike Air Max Plus (TN)', sizes:[], note:'holográfico', price:null, image:'img/produto-air-max-plus-tn.jpg' },
  { brand:'Nike', name:'Nike Mercurial Superfly — campo', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-nike-laranja-campo.webp', images:['img/chuteira-nike-laranja-campo.webp','img/chuteira-nike-cinza-campo.webp'], colorOptions:[{name:'Coral',swatch:'#ff5b47'},{name:'Cinza e rosa',swatch:'linear-gradient(135deg,#c9c9ca 0 58%,#f191b2 58%)'}], category:'Chuteiras', orderOnly:true },
  { brand:'Adidas', name:'Adidas Predator — campo', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-adidas-branca-laranja-campo.webp', images:['img/chuteira-adidas-branca-laranja-campo.webp','img/chuteira-adidas-branca-verde-campo.webp'], colorOptions:[{name:'Branco e coral',swatch:'linear-gradient(135deg,#f7f5ef 0 62%,#ff5a43 62%)'},{name:'Branco e verde',swatch:'linear-gradient(135deg,#f7f7f4 0 62%,#176b54 62%)'}], category:'Chuteiras', orderOnly:true },
  { brand:'Adidas', name:'Adidas Predator — society', sizes:[], note:'Somente por encomenda', price:null, image:'img/chuteira-adidas-preta-society.webp', category:'Chuteiras', orderOnly:true },
  { brand:'Nike', name:'Nike Mercurial Superfly — society', sizes:[], note:'4 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-nike-azul-society.webp', images:['img/chuteira-nike-azul-society.webp','img/chuteira-nike-cinza-society.webp','img/chuteira-nike-branca-laranja-society.webp','img/chuteira-nike-rosa-society.webp'], colorOptions:[{name:'Azul',swatch:'#28a9df'},{name:'Cinza',swatch:'#b8b7b5'},{name:'Branco e laranja',swatch:'linear-gradient(135deg,#f4f2ec 0 62%,#ff641f 62%)'},{name:'Rosa',swatch:'#ff6f86'}], category:'Chuteiras', orderOnly:true },
  { brand:'Nike', name:'Nike Air Max Plus/TN — várias cores', sizes:[], note:'37 cores disponíveis · somente por encomenda', price:null, image:'img/order-tn-01.webp', images:[
    'img/order-tn-01.webp','img/order-tn-02.webp','img/order-tn-03.webp','img/order-tn-04.webp','img/order-tn-05.webp','img/order-tn-06.webp','img/order-tn-07.webp','img/order-tn-08.webp','img/order-tn-09.webp','img/order-tn-10.webp','img/order-tn-11.webp','img/order-tn-12.webp','img/order-tn-13.webp','img/order-tn-14.webp','img/order-tn-15.webp','img/order-tn-16.webp','img/order-tn-17.webp','img/order-tn-18.webp','img/order-tn-19.webp','img/order-tn-20.webp','img/order-tn-21.webp','img/order-tn-22.webp','img/order-tn-23.webp','img/order-tn-24.webp','img/order-tn-25.webp','img/order-tn-26.webp','img/order-tn-27.webp','img/order-tn-28.webp','img/order-tn-29.webp','img/order-tn-30.webp','img/order-tn-31.webp','img/order-tn-32.webp','img/order-tn-33.webp','img/order-tn-34.webp','img/order-tn-35.webp','img/order-tn-36.webp','img/importado-nike-air-max-plus-prata.webp'
  ], category:'Nike TN', orderOnly:true },
  { brand:'Nike', name:'Nike Air VaporMax 2023 Flyknit — várias cores', sizes:[], note:'5 cores disponíveis · somente por encomenda', price:null, image:'img/order-vapormax-01.webp', images:['img/order-vapormax-01.webp','img/order-vapormax-02.webp','img/order-vapormax-03.webp','img/order-vapormax-04.webp','img/order-vapormax-05.webp'], colorOptions:[{name:'Preto',swatch:'#17191d'},{name:'Branco',swatch:'#f3f3ef'},{name:'Branco e preto',swatch:'linear-gradient(135deg,#f4f4f0 0 58%,#17181b 58%)'},{name:'Bordô',swatch:'#8d2937'},{name:'Cinza escuro',swatch:'#4f5661'}], category:'Nike VaporMax', orderOnly:true },
  { brand:'Nike', name:'Nike Shox TL — várias cores', sizes:[], note:'7 cores disponíveis · somente por encomenda', price:null, image:'img/order-shox-01.webp', images:['img/order-shox-01.webp','img/order-shox-02.webp','img/order-shox-03.webp','img/order-shox-04.webp','img/order-shox-05.webp','img/order-shox-06.webp','img/order-shox-07.webp'], category:'Nike Shox', orderOnly:true },
  { brand:'Nike', name:'Nike Zoom Fly 6 Premium — Ekiden', sizes:[], note:'Somente por encomenda', price:null, image:'img/order-nike-running-01.webp', category:'Nike Running', orderOnly:true },
  { brand:'Nike', name:'Nike Pegasus Premium — 2 cores', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/order-nike-running-02.webp', images:['img/order-nike-running-02.webp','img/order-nike-running-03.webp'], colorOptions:[{name:'Verde-menta e branco',swatch:'linear-gradient(135deg,#90e5d2 0 52%,#f0f1ed 52%)'},{name:'Laranja',swatch:'#ff4c28'}], category:'Nike Running', orderOnly:true },
  { brand:'Adidas', name:'Adidas Adizero Adios Pro 2 — 3 cores', sizes:[38,39,40,41,42,43], note:'3 cores disponíveis · Importado · somente por encomenda', price:null, image:'img/importado-adidas-adizero-azul.webp', images:['img/importado-adidas-adizero-azul.webp','img/importado-adidas-adizero-neon.webp','img/importado-adidas-adizero-azul-neon.webp'], colorOptions:[{name:'Azul e coral',swatch:'linear-gradient(135deg,#173f88 0 62%,#ff684f 62%)'},{name:'Amarelo neon',swatch:'#dcf400'},{name:'Azul e neon',swatch:'linear-gradient(135deg,#1686d9 0 62%,#c9ef00 62%)'}], category:'Importados', orderOnly:true },
  { brand:'Louis Vuitton', name:'Louis Vuitton Archlight branco e preto', sizes:[], note:'Nacional · somente por encomenda', price:null, image:'img/nacional-casual-branco-preto.webp', category:'Nacionais', orderOnly:true },
  { brand:'Gucci', name:'Gucci Rhyton — 2 cores', sizes:[], note:'2 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/nacional-casual-preto-verde-vermelho.webp', images:['img/nacional-casual-preto-verde-vermelho.webp','img/nacional-casual-branco-verde-vermelho.webp'], colorOptions:[{name:'Preto',swatch:'#141414'},{name:'Branco',swatch:'#f2f0e8'}], category:'Nacionais', orderOnly:true },
  { brand:'Adidas', name:'Adidas Samba — várias cores', sizes:[], note:'6 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/order-samba-branco-preto.webp', images:['img/order-samba-branco-preto.webp','img/nacional-adidas-samba-marrom.webp','img/nacional-adidas-samba-branco-verde.webp','img/nacional-adidas-samba-branco-vermelho.webp','img/nacional-adidas-samba-preto.webp','img/nacional-adidas-samba-off-white.webp'], category:'Nacionais', orderOnly:true },
  { brand:'Nike', name:'Nike Air Force 1 — várias cores', sizes:[], note:'8 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/nacional-air-force-cinza-grafite.webp', images:['img/nacional-air-force-cinza-grafite.webp','img/nacional-air-force-off-white-azul.webp','img/nacional-air-force-cinza-branco.webp','img/nacional-air-force-bege-marrom.webp','img/nacional-air-force-branco-roxo-amarelo.webp','img/nacional-air-force-creme-azul.webp','img/nacional-air-force-branco-mesh.webp','img/nacional-air-force-branco-marinho.webp'], category:'Nacionais', orderOnly:true },
  { brand:'New Balance', name:'New Balance 9060 — várias cores', sizes:[], note:'5 cores disponíveis · somente por encomenda', price:null, image:'img/nb9060-marrom-escuro.webp', images:['img/nb9060-marrom-escuro.webp','img/nb9060-bege-cinza.webp','img/nb9060-marrom-creme.webp','img/nb9060-cinza-lilas.webp','img/nb9060-marinho.webp'], colorOptions:[{name:'Marrom escuro',swatch:'#543629'},{name:'Bege e cinza',swatch:'linear-gradient(135deg,#cbbba9 0 56%,#77716d 56%)'},{name:'Marrom e creme',swatch:'linear-gradient(135deg,#86522f 0 56%,#e4d9c8 56%)'},{name:'Cinza e lilás',swatch:'linear-gradient(135deg,#8c8988 0 56%,#b7a8c7 56%)'},{name:'Azul-marinho',swatch:'#26364d'}], category:'New Balance 9060', orderOnly:true }
];

window.copyProductAndOpenDirect = async function(productName, sizeText, orderOnly = false) {
  const message = orderOnly
    ? `Olá! Tenho interesse em encomendar a ${productName}. Pode me passar os tamanhos disponíveis, valor e prazo?`
    : `Olá! Tenho interesse no ${productName}${sizeText ? `, tamanho ${sizeText}` : ''}. Pode me passar mais informações?`;
  window.open(`https://wa.me/5524999485839?text=${encodeURIComponent(message)}`, '_blank', 'noopener');
  try { await navigator.clipboard.writeText(message); } catch (_) {}
  return message;
};
