window.WELL_PRODUCTS = [
  { brand:'Lacoste', name:'Lacoste branco', sizes:[], note:'Pronta entrega', price:null, image:'img/ready-lacoste-branco.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 bege/marrom', sizes:[], note:'Pronta entrega', price:150, image:'img/ready-af1-bege-marrom.jpg' },
  { brand:'New Balance', name:'New Balance 9060 branco/cinza', sizes:[35], note:'Pronta entrega', price:125, image:'img/ready-nb9060-branco-cinza.jpg' },
  { brand:'Nike', name:'Nike ZoomX preto', sizes:[36,37], cardNote:'4 pares disponíveis', note:'2 pares no tam. 36 · 2 pares no tam. 37', price:170, image:'img/ready-nike-zoomx-preto.jpg' },
  { brand:'Nike', name:'Nike ZoomX bege/prata', sizes:[40], note:'', price:150, image:'img/ready-nike-zoomx-bege-prata.jpg' },
  { brand:'Nike', name:'Nike ZoomX Invincible Run 3 azul', sizes:[40,41], cardNote:'3 pares disponíveis', note:'1 par no tam. 40 · 2 pares no tam. 41', price:150, image:'img/ready-nike-zoomx-invincible-azul.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 preto', sizes:[39,41], note:'', price:250, image:'img/ready-af1-preto.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 branco', sizes:[37,41], cardNote:'cadarços extras', note:'Tam. 37: opções com cadarços branco trançado/normal ou cetim creme/branco · tam. 41: 2 cadarços brancos', price:250, image:'img/ready-af1-branco-37-trancado.jpg', images:['img/ready-af1-branco-37-trancado.jpg','img/ready-af1-branco-37.jpg','img/ready-af1-branco-41.jpg'] },
  { brand:'Nike', name:'Nike Air Force 1 cinza', sizes:[41,43], note:'', price:250, image:'img/produto-af1-cinza.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 bege/rosa', sizes:[36], note:'2 tipos de cadarço', price:250, image:'img/ready-af1-bege-rosa.jpg' },
  { brand:'Nike', name:'Nike AF1 Shadow azul/rosa', sizes:[37], note:'cadarços de cetim e branco', price:250, image:'img/ready-af1-shadow-azul-rosa.jpg' },
  { brand:'Nike', name:'Nike Air Force 1 preto/branco', sizes:[38], note:'2 cadarços: preto e creme', price:250, image:'img/ready-af1-panda.jpg' },
  { brand:'Nike', name:'Nike AF1 plataforma azul', sizes:[36,37], note:'2 cadarços: azul e branco', price:250, image:'img/ready-af1-plataforma-azul.jpg' },
  { brand:'Nike', name:'Nike Court branco/azul', sizes:[37,39], note:'2 cadarços: azul e branco', price:250, image:'img/ready-nike-court-branco-azul.jpg' },
  { brand:'Adidas', name:'Adidas Samba', sizes:[37], note:'2 cadarços: branco e preto', price:170, image:'img/ready-adidas-samba.jpg' },
  { brand:'Adidas', name:'Adidas SL72 areia', sizes:[37], note:'2 cadarços: branco e preto', price:250, image:'img/ready-adidas-sl72-areia.jpg' },
  { brand:'Adidas', name:'Adidas SL72 bordô', sizes:[38], note:'feminino', price:250, image:'img/ready-adidas-sl72-bordo.jpg' },
  { brand:'Adidas', name:'Adidas feminino branco', sizes:[36,37,39], cardNote:'4 pares disponíveis', note:'1 par no tam. 36 · 2 pares no tam. 37 · 1 par no tam. 39', price:170, image:'img/ready-adidas-feminino-branco.jpg' },
  { brand:'On Cloud', name:'On Cloud preto', sizes:[36,37], note:'', price:null, image:'img/produto-on-cloud-preto.jpg' },
  { brand:'Nike', name:'Nike Air Max Plus (TN)', sizes:[], note:'holográfico', price:null, image:'img/produto-air-max-plus-tn.jpg' },
  { brand:'Nike', name:'Nike Mercurial Superfly — campo', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-nike-laranja-campo.webp', images:['img/chuteira-nike-laranja-campo.webp','img/chuteira-nike-cinza-campo.webp'], colorOptions:[{name:'Coral',swatch:'#ff5b47'},{name:'Cinza e rosa',swatch:'linear-gradient(135deg,#c9c9ca 0 58%,#f191b2 58%)'}], category:'Chuteiras', orderOnly:true },
  { brand:'Adidas', name:'Adidas Predator — campo', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-adidas-branca-laranja-campo.webp', images:['img/chuteira-adidas-branca-laranja-campo.webp','img/chuteira-adidas-branca-verde-campo.webp'], colorOptions:[{name:'Branco e coral',swatch:'linear-gradient(135deg,#f7f5ef 0 62%,#ff5a43 62%)'},{name:'Branco e verde',swatch:'linear-gradient(135deg,#f7f7f4 0 62%,#176b54 62%)'}], category:'Chuteiras', orderOnly:true },
  { brand:'Adidas', name:'Adidas Predator — society', sizes:[], note:'Somente por encomenda', price:null, image:'img/chuteira-adidas-preta-society.webp', category:'Chuteiras', orderOnly:true },
  { brand:'Nike', name:'Nike Mercurial Superfly — society', sizes:[], note:'4 cores disponíveis · somente por encomenda', price:null, image:'img/chuteira-nike-azul-society.webp', images:['img/chuteira-nike-azul-society.webp','img/chuteira-nike-cinza-society.webp','img/chuteira-nike-branca-laranja-society.webp','img/chuteira-nike-rosa-society.webp'], colorOptions:[{name:'Azul',swatch:'#28a9df'},{name:'Cinza',swatch:'#b8b7b5'},{name:'Branco e laranja',swatch:'linear-gradient(135deg,#f4f2ec 0 62%,#ff641f 62%)'},{name:'Rosa',swatch:'#ff6f86'}], category:'Chuteiras', orderOnly:true },
  { brand:'Nike', name:'Nike Air Max Plus/TN — várias cores', sizes:[], note:'37 cores disponíveis · somente por encomenda', price:null, image:'img/order-tn-01.webp', images:[
    'img/order-tn-01.webp','img/order-tn-02.webp','img/order-tn-03.webp','img/order-tn-04.webp','img/order-tn-05.webp','img/order-tn-06.webp','img/order-tn-07.webp','img/order-tn-08.webp','img/order-tn-09.webp','img/order-tn-10.webp','img/order-tn-11.webp','img/order-tn-12.webp','img/order-tn-13.webp','img/order-tn-14.webp','img/order-tn-15.webp','img/order-tn-16.webp','img/order-tn-17.webp','img/order-tn-18.webp','img/order-tn-19.webp','img/order-tn-20.webp','img/order-tn-21.webp','img/order-tn-22.webp','img/order-tn-23.webp','img/order-tn-24.webp','img/order-tn-25.webp','img/order-tn-26.webp','img/order-tn-27.webp','img/order-tn-28.webp','img/order-tn-29.webp','img/order-tn-30.webp','img/order-tn-31.webp','img/order-tn-32.webp','img/order-tn-33.webp','img/order-tn-34.webp','img/order-tn-35.webp','img/order-tn-36.webp','img/importado-nike-air-max-plus-prata.webp'
  ], colorOptions:[
    {name:'Roxo e pink',swatch:'linear-gradient(135deg,#38265f 0 55%,#e42b88 55%)'},{name:'Pink e azul',swatch:'linear-gradient(135deg,#ed2b91 0 55%,#3a3591 55%)'},{name:'Preto estampado',swatch:'linear-gradient(135deg,#17191b 0 68%,#29765d 68%)'},{name:'Preto e azul',swatch:'linear-gradient(135deg,#111923 0 58%,#0877d8 58%)'},{name:'Azul e preto',swatch:'linear-gradient(135deg,#1687bd 0 55%,#11161d 55%)'},{name:'Grafite',swatch:'#51545d'},{name:'Azul e roxo',swatch:'linear-gradient(135deg,#344392 0 55%,#7753ba 55%)'},{name:'Preto total',swatch:'#111315'},{name:'Pink e roxo',swatch:'linear-gradient(135deg,#e20b85 0 55%,#762678 55%)'},{name:'Cinza e preto',swatch:'linear-gradient(135deg,#aeb0b5 0 55%,#191c22 55%)'},{name:'Preto e branco',swatch:'linear-gradient(135deg,#15171a 0 55%,#f2f2ef 55%)'},{name:'Branco e roxo',swatch:'linear-gradient(135deg,#f3f3ef 0 55%,#745fc9 55%)'},{name:'Azul-claro',swatch:'#76b4dc'},{name:'Azul vivo e preto',swatch:'linear-gradient(135deg,#1688ce 0 55%,#10161e 55%)'},{name:'Vermelho e azul',swatch:'linear-gradient(135deg,#e2293f 0 55%,#245aa0 55%)'},{name:'Preto e roxo',swatch:'linear-gradient(135deg,#15171b 0 58%,#482660 58%)'},{name:'Branco e azul',swatch:'linear-gradient(135deg,#f3f3ef 0 58%,#2f83ce 58%)'},{name:'Branco e turquesa',swatch:'linear-gradient(135deg,#f3f3ef 0 58%,#27a8b7 58%)'},{name:'Preto, branco e lilás',swatch:'linear-gradient(135deg,#17191c 0 48%,#f2f2ef 48% 76%,#b6a7cc 76%)'},{name:'Vermelho e preto',swatch:'linear-gradient(135deg,#d82334 0 55%,#17191c 55%)'},{name:'Branco e cinza',swatch:'linear-gradient(135deg,#f2f2ef 0 58%,#aeb3bd 58%)'},{name:'Branco e rosa-claro',swatch:'linear-gradient(135deg,#f5f3f2 0 58%,#efb7c8 58%)'},{name:'Branco e vinho',swatch:'linear-gradient(135deg,#f3f3ef 0 58%,#9a3354 58%)'},{name:'Branco e verde',swatch:'linear-gradient(135deg,#f3f3ef 0 58%,#17624d 58%)'},{name:'Branco e preto clássico',swatch:'linear-gradient(135deg,#f2f2ef 0 55%,#16181b 55%)'},{name:'Roxo, pink e amarelo',swatch:'linear-gradient(135deg,#632f80 0 44%,#d91b88 44% 76%,#e3aa28 76%)'},{name:'Branco total',swatch:'#f4f4f1'},{name:'Preto e branco II',swatch:'linear-gradient(135deg,#111315 0 58%,#f4f4f1 58%)'},{name:'Branco, preto e verde',swatch:'linear-gradient(135deg,#f3f3ef 0 44%,#16181b 44% 74%,#2a8a69 74%)'},{name:'Preto e turquesa',swatch:'linear-gradient(135deg,#11151a 0 62%,#0795a8 62%)'},{name:'Branco e preto invertido',swatch:'linear-gradient(135deg,#f3f3ef 0 50%,#111318 50%)'},{name:'Preto com sola branca',swatch:'linear-gradient(135deg,#111318 0 62%,#f3f3ef 62%)'},{name:'Branco e verde-escuro',swatch:'linear-gradient(135deg,#f3f3ef 0 62%,#12604c 62%)'},{name:'Preto com strass',swatch:'linear-gradient(135deg,#111315 0 70%,#c4c7cd 70%)'},{name:'Laranja e vermelho',swatch:'linear-gradient(135deg,#f4933b 0 52%,#e32632 52%)'},{name:'Roxo e laranja',swatch:'linear-gradient(135deg,#4f2b91 0 62%,#ff7b31 62%)'},{name:'Prata e preto',swatch:'linear-gradient(135deg,#c3c5c8 0 58%,#15171a 58%)'}
  ], category:'Nike TN', orderOnly:true },
  { brand:'Nike', name:'Nike Air Max Dn8 — 4 cores', sizes:[], note:'4 cores disponíveis · Importado · somente por encomenda', price:null, image:'img/order-nike-dn8-preto.jpg', images:['img/order-nike-dn8-preto.jpg','img/order-nike-dn8-offwhite-preto.jpg','img/order-nike-dn8-branco-dourado.jpg','img/order-nike-dn8-azul-preto.jpg'], colorOptions:[{name:'Preto',swatch:'#11161d'},{name:'Off-white e preto',swatch:'linear-gradient(135deg,#e7e1d2 0 58%,#171a20 58%)'},{name:'Branco e dourado',swatch:'linear-gradient(135deg,#f2f2ed 0 62%,#b78f2e 62%)'},{name:'Azul e preto',swatch:'linear-gradient(135deg,#9bcbe6 0 58%,#11161d 58%)'}], category:'Importados', orderOnly:true },
  { brand:'Nike', name:'Nike Air VaporMax 2023 Flyknit — várias cores', sizes:[], note:'5 cores disponíveis · somente por encomenda', price:null, image:'img/order-vapormax-01.webp', images:['img/order-vapormax-01.webp','img/order-vapormax-02.webp','img/order-vapormax-03.webp','img/order-vapormax-04.webp','img/order-vapormax-05.webp'], colorOptions:[{name:'Preto',swatch:'#17191d'},{name:'Branco',swatch:'#f3f3ef'},{name:'Branco e preto',swatch:'linear-gradient(135deg,#f4f4f0 0 58%,#17181b 58%)'},{name:'Bordô',swatch:'#8d2937'},{name:'Cinza escuro',swatch:'#4f5661'}], category:'Nike VaporMax', orderOnly:true },
  { brand:'Nike', name:'Nike Shox TL — várias cores', sizes:[], note:'7 cores disponíveis · somente por encomenda', price:null, image:'img/order-shox-01.webp', images:['img/order-shox-01.webp','img/order-shox-02.webp','img/order-shox-03.webp','img/order-shox-04.webp','img/order-shox-05.webp','img/order-shox-06.webp','img/order-shox-07.webp'], colorOptions:[{name:'Branco e prata',swatch:'linear-gradient(135deg,#f4f4f1 0 62%,#bfc1c3 62%)'},{name:'Azul-claro e prata',swatch:'linear-gradient(135deg,#a9cfdf 0 58%,#c7c9ca 58%)'},{name:'Azul e preto',swatch:'linear-gradient(135deg,#7baec5 0 54%,#111720 54%)'},{name:'Preto',swatch:'#111418'},{name:'Preto e branco',swatch:'linear-gradient(135deg,#111418 0 58%,#eff3f2 58%)'},{name:'Branco, cinza e preto',swatch:'linear-gradient(135deg,#f3f3ef 0 42%,#aab1b7 42% 72%,#15191e 72%)'},{name:'Azul-claro e preto',swatch:'linear-gradient(135deg,#91bdd0 0 58%,#11161d 58%)'}], category:'Nike Shox', orderOnly:true },
  { brand:'Nike', name:'Nike Zoom Fly 6 Premium — Ekiden', sizes:[], note:'Somente por encomenda', price:null, image:'img/order-nike-running-01.webp', category:'Nike Running', orderOnly:true },
  { brand:'Nike', name:'Nike Pegasus Premium — 2 cores', sizes:[], note:'2 cores disponíveis · somente por encomenda', price:null, image:'img/order-nike-running-02.webp', images:['img/order-nike-running-02.webp','img/order-nike-running-03.webp'], colorOptions:[{name:'Verde-menta e branco',swatch:'linear-gradient(135deg,#90e5d2 0 52%,#f0f1ed 52%)'},{name:'Laranja',swatch:'#ff4c28'}], category:'Nike Running', orderOnly:true },
  { brand:'Adidas', name:'Adidas Adizero Adios Pro 2 — 3 cores', sizes:[38,39,40,41,42,43], note:'3 cores disponíveis · Importado · somente por encomenda', price:null, image:'img/importado-adidas-adizero-azul.webp', images:['img/importado-adidas-adizero-azul.webp','img/importado-adidas-adizero-neon.webp','img/importado-adidas-adizero-azul-neon.webp'], colorOptions:[{name:'Azul e coral',swatch:'linear-gradient(135deg,#173f88 0 62%,#ff684f 62%)'},{name:'Amarelo neon',swatch:'#dcf400'},{name:'Azul e neon',swatch:'linear-gradient(135deg,#1686d9 0 62%,#c9ef00 62%)'}], category:'Importados', orderOnly:true },
  { brand:'Adidas', name:'Adidas Hyperboost — 3 cores', sizes:[], note:'3 cores disponíveis · Importado · somente por encomenda', price:null, image:'img/order-adidas-hyperboost-preto.jpg', images:['img/order-adidas-hyperboost-preto.jpg','img/order-adidas-hyperboost-branco-vermelho.jpg','img/order-adidas-hyperboost-branco-neon.jpg'], colorOptions:[{name:'Preto e cinza',swatch:'linear-gradient(135deg,#14171b 0 62%,#6f7882 62%)'},{name:'Branco e vermelho',swatch:'linear-gradient(135deg,#f3f1eb 0 58%,#cf1f36 58%)'},{name:'Branco e amarelo neon',swatch:'linear-gradient(135deg,#f3f1eb 0 58%,#dfff00 58%)'}], category:'Importados', orderOnly:true },
  { brand:'Louis Vuitton', name:'Louis Vuitton Archlight branco e preto', sizes:[], note:'Nacional · somente por encomenda', price:null, image:'img/nacional-casual-branco-preto.webp', category:'Nacionais', orderOnly:true },
  { brand:'Gucci', name:'Gucci Rhyton — 2 cores', sizes:[], note:'2 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/nacional-casual-preto-verde-vermelho.webp', images:['img/nacional-casual-preto-verde-vermelho.webp','img/nacional-casual-branco-verde-vermelho.webp'], colorOptions:[{name:'Preto',swatch:'#141414'},{name:'Branco',swatch:'#f2f0e8'}], category:'Nacionais', orderOnly:true },
  { brand:'Adidas', name:'Adidas Samba — várias cores', sizes:[], note:'6 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/order-samba-branco-preto.webp', images:['img/order-samba-branco-preto.webp','img/nacional-adidas-samba-marrom.webp','img/nacional-adidas-samba-branco-verde.webp','img/nacional-adidas-samba-branco-vermelho.webp','img/nacional-adidas-samba-preto.webp','img/nacional-adidas-samba-off-white.webp'], colorOptions:[{name:'Branco e preto',swatch:'linear-gradient(135deg,#f2f0e9 0 58%,#151515 58%)'},{name:'Marrom',swatch:'#49372f'},{name:'Branco e verde',swatch:'linear-gradient(135deg,#f1f0eb 0 58%,#23815d 58%)'},{name:'Branco e vermelho',swatch:'linear-gradient(135deg,#f2f1ed 0 58%,#d83638 58%)'},{name:'Preto e branco',swatch:'linear-gradient(135deg,#151515 0 58%,#f1f0eb 58%)'},{name:'Off-white',swatch:'#ddd9cd'}], category:'Nacionais', orderOnly:true },
  { brand:'Nike', name:'Nike Air Force 1 — várias cores', sizes:[], note:'8 cores disponíveis · Nacional · somente por encomenda', price:null, image:'img/nacional-air-force-cinza-grafite.webp', images:['img/nacional-air-force-cinza-grafite.webp','img/nacional-air-force-off-white-azul.webp','img/nacional-air-force-cinza-branco.webp','img/nacional-air-force-bege-marrom.webp','img/nacional-air-force-branco-roxo-amarelo.webp','img/nacional-air-force-creme-azul.webp','img/nacional-air-force-branco-mesh.webp','img/nacional-air-force-branco-marinho.webp'], colorOptions:[{name:'Cinza e grafite',swatch:'linear-gradient(135deg,#c3c4c1 0 58%,#55575b 58%)'},{name:'Off-white e azul-claro',swatch:'linear-gradient(135deg,#e9e5da 0 58%,#70b3e1 58%)'},{name:'Cinza e branco',swatch:'linear-gradient(135deg,#74777c 0 58%,#f1f1ed 58%)'},{name:'Bege e marrom',swatch:'linear-gradient(135deg,#d5ccbb 0 58%,#766050 58%)'},{name:'Branco, roxo e amarelo',swatch:'linear-gradient(135deg,#f3f2ed 0 42%,#552a8b 42% 72%,#e8b52f 72%)'},{name:'Creme e azul',swatch:'linear-gradient(135deg,#e8dfcc 0 58%,#61a8db 58%)'},{name:'Branco mesh',swatch:'#f2f2ef'},{name:'Branco e marinho',swatch:'linear-gradient(135deg,#f2f2ef 0 58%,#1d365c 58%)'}], category:'Nacionais', orderOnly:true },
  { brand:'New Balance', name:'New Balance 2000 preto', sizes:[38,39,40,41,42,43], note:'Importado · somente por encomenda', price:null, image:'img/order-nb2000-preto-01.jpg', images:['img/order-nb2000-preto-01.jpg','img/order-nb2000-preto-02.jpg','img/order-nb2000-preto-03.jpg'], category:'Importados', orderOnly:true },
  { brand:'New Balance', name:'New Balance 9060 — várias cores', sizes:[], note:'5 cores disponíveis · somente por encomenda', price:null, image:'img/nb9060-marrom-escuro.webp', images:['img/nb9060-marrom-escuro.webp','img/nb9060-bege-cinza.webp','img/nb9060-marrom-creme.webp','img/nb9060-cinza-lilas.webp','img/nb9060-marinho.webp'], colorOptions:[{name:'Marrom escuro',swatch:'#543629'},{name:'Bege e cinza',swatch:'linear-gradient(135deg,#cbbba9 0 56%,#77716d 56%)'},{name:'Marrom e creme',swatch:'linear-gradient(135deg,#86522f 0 56%,#e4d9c8 56%)'},{name:'Cinza e lilás',swatch:'linear-gradient(135deg,#8c8988 0 56%,#b7a8c7 56%)'},{name:'Azul-marinho',swatch:'#26364d'}], category:'New Balance 9060', orderOnly:true }
];

window.copyProductAndOpenDirect = async function(productName, sizeText, orderOnly = false) {
  const message = orderOnly
    ? `Olá! Tenho interesse em encomendar a ${productName}. Pode me passar os tamanhos disponíveis, valor e prazo?`
    : `Olá! Tenho interesse no ${productName}${sizeText ? `, tamanho ${sizeText}` : ''}. Pode me passar mais informações?`;
  window.open(`https://wa.me/5524999485839?text=${encodeURIComponent(message)}`, '_blank', 'noopener');
  try { await navigator.clipboard.writeText(message); } catch (_) {}
  return message;
};
